---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: hpe-filex-csi-controller-scc
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:hpe-storage:hpe-filex-csi-controller-sa
volumes:
- hostPath
- emptyDir
- projected
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: hpe-filex-csi-node-scc
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- SYS_ADMIN
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups: []
priority:
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:hpe-storage:hpe-filex-csi-node-sa
volumes:
- emptyDir
- hostPath
- projected
