apiVersion: batch/v1
kind: Job
metadata:
  name: pvc-copy-file
spec:
  template:
    spec:
      containers:
        - name: rsync
          image: quay.io/hpestorage/pvc-copy-util:v1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: src-pv
              mountPath: /src
            - name: dst-pv
              mountPath: /dst
          command: 
            - rsync
          args: 
            - -avzh
            - -O
            - --progress
            - --append-verify
            - --numeric-ids
            - /src/
            - /dst
      restartPolicy: Never
      volumes:
      - name: src-pv
        persistentVolumeClaim:
          claimName: old-pvc
      - name: dst-pv
        persistentVolumeClaim:
          claimName: new-pvc
