kind: ConfigMap
apiVersion: v1
metadata:
  name: hpe-nfs-conf
data:
  ganesha.conf: |2-

    NFS_Core_Param
    {
      NFS_Protocols= 4;
      NFS_Port = 2049;
      fsid_device = false;
    }
    NFSv4
    {
      Graceless = true;
      UseGetpwnam = true;
      DomainName = "$(CLUSTER_NODE_DOMAIN_NAME)";
    }
    EXPORT
    {
      Export_Id = 716;
      Path = /export;
      Pseudo = /export;
      Access_Type = RW;
      Squash = No_Root_Squash;
      Transports = TCP;
      Protocols = 4;
      SecType = "sys";
      FSAL {
          Name = VFS;
      }
    }
