apiVersion: v1
kind: Service
metadata:
  name: hpe-nfs
spec:
  ports:
  - name: grpc
    port: 49000
    protocol: TCP
    targetPort: 49000
  - name: nfs-tcp
    port: 2049
    protocol: TCP
    targetPort: 2049
  - name: nfs-udp
    port: 2049
    protocol: UDP
    targetPort: 2049
  - name: nlockmgr-tcp
    port: 32803
    protocol: TCP
    targetPort: 32803
  - name: nlockmgr-udp
    port: 32803
    protocol: UDP
    targetPort: 32803
  - name: mountd-tcp
    port: 20048
    protocol: TCP
    targetPort: 20048
  - name: mountd-udp
    port: 20048
    protocol: UDP
    targetPort: 20048
  - name: portmapper-tcp
    port: 111
    protocol: TCP
    targetPort: 111
  - name: portmapper-udp
    port: 111
    protocol: UDP
    targetPort: 111
  - name: statd-tcp
    port: 662
    protocol: TCP
    targetPort: 662
  - name: statd-udp
    port: 662
    protocol: UDP
    targetPort: 662
  - name: rquotad-tcp
    port: 875
    protocol: TCP
    targetPort: 875
  - name: rquotad-udp
    port: 875
    protocol: UDP
    targetPort: 875
  selector:
    app: $(SERVICE_SELECTOR)
  sessionAffinity: None
  type: ClusterIP
