---
apiVersion: storage.hpe.com/v1
kind: HPECSIDriver
metadata:
  name: csi-driver
spec:
  disable:
    nimble: false
    primera: false
    alletra6000: false
    alletra9000: false
    alletraStorageMP: false
  imagePullPolicy: IfNotPresent
  logLevel: info
  disableNodeConformance: false
  disableNodeConfiguration: false
  iscsi:
    chapUser: ''
    chapPassword: ''
  registry: quay.io
  kubeletRootDir: "/var/lib/kubelet/"
  disableNodeGetVolumeStats: false
  controller:
    affinity: {}
    labels: {}
    nodeSelector: {}
    tolerations: []
  csp:
    affinity: {}
    labels: {}
    nodeSelector: {}
    tolerations: []
  node:
    affinity: {}
    labels: {}
    nodeSelector: {}
    tolerations: []
